<a href="https://colab.research.google.com/github/snehi04/Machine-Learning-Using-Python/blob/master/Naive_Bayes_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!apt-get -qq install -y graphviz && pip install -q pydot
!pip install graphviz
!pip install pydot

In [0]:
#Importing Packages
import pandas as pd
from sklearn import datasets
from matplotlib import pyplot
from matplotlib import pyplot
from matplotlib import pylab
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_graphviz
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from pydot import graph_from_dot_data
#https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip

In [0]:
#Test and Train Dataset Creation
data_train = datasets.fetch_20newsgroups(subset='train')
data_test = datasets.fetch_20newsgroups(subset='test')


In [0]:
data_20

<function sklearn.datasets.twenty_newsgroups.fetch_20newsgroups>

In [0]:
data_train.data[:10]

In [0]:
print(vectors_train.shape)
print(vectors_test.shape)

In [0]:
data_train = datasets.fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))

In [0]:
data_train.data[:10]

In [0]:
#Conversion of text data into vectors
vectorizer = CountVectorizer()
vectors_train20=vectorizer.fit_transform(data_train.data)
vectors_test20=vectorizer.transform(data_test.data)

In [79]:
#Implmentation of Multinomial Naive Bayes
nb = MultinomialNB(alpha=.1)
nb.fit(vectors_train20, data_train.target)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [0]:
#Confusion Matrix to predict visualization
confusion_matrix(nb.predict(vectors_test20), data_test.target)

In [0]:
#Implementing Tf-Idf Vectorizer and Checking the accuracy
vectorizer1 = TfidfVectorizer()
vectors_train1 = vectorizer1.fit_transform(data_train.data)
vectors_test1 = vectorizer1.transform(data_test.data)

In [82]:
print(vectors_train1.shape)
print(vectors_test1.shape)

(11314, 101631)
(7532, 93564)


In [0]:
print(vectors_train1)

In [91]:
#Naive Bayes Implementation
nb = MultinomialNB(alpha=.1)
nb.fit(vectors_train1, data_train.target)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [0]:
#Confusion Matrix to check the accuracy
confusion_matrix(nb.predict(vectors_test1), data_test.target)

**When we use tf-idf vectoriser, performance of the model has improved.**



```

```

**Spam or Ham**

Checking the Model Accuracy on Spam or Ham Dataset of Logistic, Decision Tree and Naive Bayes

In [0]:
def fetch_sms_spam():
  import requests # requests is a handy http library
  import zipfile # a zip library
  r=requests.get('http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/smsspamcollection.zip')
  # I know of know way to get data out of a zipfile without saving to disk extracting and reading in, sigh
  zf=open('smsspam.zip','wb')
  zf.write(r.content)
  zip_ref = zipfile.ZipFile('smsspam.zip', 'r')
  zip_ref.extractall('smsspam')
  zip_ref.close()
  zf.close
  sms_file=open('smsspam/SMSSpamCollection.txt','r')
  #object to return
  data = {'data':[], 'target':[], 'target_classes': ['ham', 'spam']}
  # First tab splits the class and the SMS message
  for line in sms_file:
    idx = line.find('\t')
    target = line[:idx]
    doc = line[idx+1:]
    data['data'] += [doc]
    if target == 'ham': data['target'] += [0]
    else: data['target'] += [1]
  sms_file.close()
  return data

In [0]:
#Fetching Dataset
data1 = fetch_sms_spam()

In [0]:
data1

In [0]:
#Splitting Data into Test and Train Data
X_train, X_test = train_test_split(data1['data'], random_state=3)
y_train, y_test = train_test_split(data1['target'], random_state=3)

In [0]:
#Converting text into vectorizer
vectorizer2 = CountVectorizer()
vectors_train2=vectorizer2.fit_transform(X_train)
vectors_test2=vectorizer2.transform(X_test)

In [30]:
print(vectors_train2.shape)
print(vectors_test2.shape)

(4180, 7520)
(1394, 7520)


In [0]:
print(vectors_train2)

In [0]:
print(vectorizer.vocabulary_)

In [19]:
#Implementing Naive Bayes
nb = MultinomialNB(alpha=.1)
nb.fit(vectors_train2, y_train)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [39]:
#Confusion Matrix ro check the accuracy
confusion_matrix(nb.predict(vectors_test2) , y_test)

array([[1207,   12],
       [  11,  164]])

**Decision Tree**

In [40]:
#Initializing Decision Tree
tree = DecisionTreeClassifier()
tree.fit(vectors_train2, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [41]:
#Confusion Matrix to check the accuracy
confusion_matrix(tree.predict(vectors_test2),y_test)

array([[1200,   34],
       [  18,  142]])

**Logistic Regression**

In [42]:
#Implementing Logistic Regression
lr = LogisticRegression()
lr.fit((vectors_train2),y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [44]:
#Confusion Matrix to Check the accuracy
confusion_matrix(lr.predict(vectors_test2),y_test)

array([[1216,   27],
       [   2,  149]])

It shows that Naive Bayes performed best on the dataset, while Decision Tree performed worst.